php 8.3 / 8.4 / 8.5 : mise à jour des images
Ajout de php-8.5-apache (trixie, opcache intégré au core), Node 24,
extensions redis/pcntl/posix en 8.3 et 8.4, webp et mysqli en 8.3.

diff --git a/php-8.3-apache/Dockerfile b/php-8.3-apache/Dockerfile
--- a/php-8.3-apache/Dockerfile
+++ b/php-8.3-apache/Dockerfile
@@ -5,7 +5,7 @@ ENV PHP_ENABLE_BLACKFIRE=false
 ENV MAGENTO_DIR=true
 ENV DOCUMENT_ROOT=/var/www/html/pub
 ENV COMPOSER_VERSION="latest"
-ENV NODE_MAJOR=22
+ENV NODE_MAJOR=24
 ENV TZ=Europe/Paris
 
 RUN pecl install xdebug
@@ -15,11 +15,13 @@ RUN apt-get update && apt-get install -y \
         libfreetype6-dev \
         libjpeg62-turbo-dev \
         libpng-dev \
+        libwebp-dev \
         libxslt-dev \
         libzip-dev \
+        moreutils \
 #        libmpdec-dev \
-    && docker-php-ext-install iconv pdo pdo_mysql zip xsl curl opcache \
-    && docker-php-ext-configure gd --with-freetype --with-jpeg \
+    && docker-php-ext-install iconv pdo pdo_mysql zip xsl curl opcache pcntl posix \
+    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
     && docker-php-ext-install gd \
     && apt-get install -y libmagickwand-dev \
     && pecl install imagick \
@@ -33,11 +35,12 @@ RUN apt-get update && apt-get install -y \
     && docker-php-ext-install ftp exif \
     # others
     && docker-php-ext-install soap bcmath sockets \
+    && docker-php-ext-install mysqli \
     # telemetry
-    && pecl install opentelemetry protobuf \
-    && docker-php-ext-enable opentelemetry protobuf \
-    # cron
-    && apt install -y cron tzdata
+    && pecl install opentelemetry protobuf redis \
+    && docker-php-ext-enable opentelemetry protobuf redis \
+    # cron & network
+    && apt install -y cron tzdata texinfo net-tools
 
 # grunt less
 RUN apt install -y ca-certificates curl gnupg \
@@ -47,8 +50,94 @@ RUN apt install -y ca-certificates curl gnupg \
     && apt update && apt install -y nodejs \
     && npm -g install grunt-cli less sass uglify-js uglifycss
 
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+# https://devdocs.magento.com/guides/v2.4/performance-best-practices/software.html
+# https://devdocs.magento.com/guides/v2.4/install-gde/prereq/php-settings.html
+RUN set -eux; \
+  { \
+  echo '<IfModule mod_expires.c>'; \
+  echo '  ExpiresActive On'; \
+  echo '  ExpiresByType image/jpg "access plus 1 year"'; \
+  echo '  ExpiresByType image/jpeg "access plus 1 year"'; \
+  echo '  ExpiresByType image/avif "access plus 1 year"'; \
+  echo '  ExpiresByType image/webp "access plus 1 year"'; \
+  echo '  ExpiresByType image/png "access plus 1 year"'; \
+  echo '  ExpiresByType text/css "access plus 1 month"'; \
+  echo '  ExpiresByType text/x-javascript "access plus 1 month"'; \
+  echo '  ExpiresByType image/x-icon "access plus 1 year"'; \
+  echo '</IfModule>'; \
+  } > /etc/apache2/conf-available/cache.conf; \
+  a2enconf cache; \
+  { \
+  echo 'MaxKeepAliveRequests 1000'; \
+  echo 'KeepAliveTimeout 2'; \
+  } > /etc/apache2/conf-available/keepalive.conf; \
+  a2enconf keepalive; \
+  docker-php-ext-enable opcache;
+# We don't want this kind of cache for local dev
+#  { \
+#    echo "opcache.huge_code_pages=1"; \
+#    echo 'opcache.memory_consumption=512'; \
+#    echo 'opcache.interned_strings_buffer=50'; \
+#    echo 'opcache.max_accelerated_files=60000'; \
+#    echo 'opcache.consistency_checks=0'; \
+#    echo 'opcache.validate_timestamps=0'; \
+#    echo 'opcache.revalidate_freq=10'; \
+#    echo 'opcache.fast_shutdown=1'; \
+#    echo 'opcache.jit=1235'; \
+#    echo 'opcache.jit_buffer_size=256M'; \
+#  } > /usr/local/etc/php/conf.d/opcache-recommended.ini
+
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+  # https://www.php.net/manual/en/errorfunc.constants.php
+  # https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+  echo 'error_reporting = -1'; \
+  echo 'display_errors = On'; \
+  echo 'display_startup_errors = On'; \
+  echo 'log_errors = On'; \
+  echo 'error_log = /var/log/php.log'; \
+  echo 'log_errors_max_len = 1024'; \
+  echo 'ignore_repeated_errors = Off'; \
+  echo 'ignore_repeated_source = Off'; \
+  echo 'html_errors = Off'; \
+  } > /usr/local/etc/php/conf.d/error-logging.ini ; \
+  { \
+  echo 'variables_order = "EGPCS"'; \
+  } > /usr/local/etc/php/conf.d/variables-order.ini ; \
+  { \
+  echo '[apcu]'; \
+  echo 'apc.enabled = 1'; \
+  echo 'apc.enable_cli = 1'; \
+  } > /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini ; \
+  docker-php-ext-enable apcu; \
+  { \
+  echo 'memory_limit = 1G'; \
+  echo 'max_input_vars = 100000'; \
+  echo 'post_max_size = 50M'; \
+  echo 'realpath_cache_size = 10M'; \
+  echo 'realpath_cache_ttl = 7200'; \
+  echo 'upload_max_filesize = 50M'; \
+  echo 'default_socket_timeout = 1200'; \
+  } > /usr/local/etc/php/conf.d/limits.ini ; \
+  { \
+    echo 'sendmail_path = "/usr/bin/msmtp -t"'; \
+  } > /usr/local/etc/php/conf.d/smtp.ini
+
 # smtp
-ADD etc/msmtprc /etc/msmtprc
+#ADD etc/msmtprc /etc/msmtprc
+RUN { \
+  echo 'defaults'; \
+  echo ''; \
+  echo 'account maildev'; \
+  echo 'host mail'; \
+  echo 'port 25'; \
+  echo 'from "user@mail.test"'; \
+  echo ''; \
+  echo 'account default : maildev'; \
+  } > /etc/msmtprc
+
 RUN apt-get install -y msmtp mailutils \
   && apt purge -y exim4-base exim4-config \
   && chmod 644 /etc/msmtprc \
@@ -82,7 +171,7 @@ RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local
 #    && rm -Rf /tmp/blackfire
 
 RUN set -eux \
-  && a2enmod rewrite expires \
+  && a2enmod rewrite expires headers \
   && a2ensite 000-default
 
 RUN \
@@ -97,6 +186,6 @@ ADD docker-entrypoint.sh /docker-entrypoint.sh
 RUN ["chmod", "+x", "/docker-entrypoint.sh"]
 ENTRYPOINT ["/docker-entrypoint.sh"]
 
-ADD php/custom.ini /usr/local/etc/php/conf.d/xxx-magento.ini
+#ADD php/custom.ini /usr/local/etc/php/conf.d/xxx-magento.ini
 
 CMD ["apache2-foreground"]
